import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import SignInPage from "./sign-in/[[...index]]";
import { UserButton } from "@clerk/clerk-react";
import Logo from "~/../public/img/logo.png";
import Image from "next/image";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex h-16 items-center justify-between px-10">
        <Image src={Logo} width={50} alt="logo" />
        <UserButton />
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <SignInPage /> */}
        <h1 className="text-[100px] text-white">ANJAY RANIIIIII</h1>
      </main>
    </>
  );
}
